name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Manus
      run: |
        npm install -g @manus-ai/cli
        manus deploy backend --project-dir .
      env:
        MANUS_API_KEY: ${{ secrets.MANUS_API_KEY }}


